### PR TITLE
Update All Assets

### PR DESCRIPTION
**Pull request by ItzLoonie**
Updates each and every asset, as well as deletes any that are not needed.

#### Other changes
- Added CompliantKillers.png (although needs to be redone)
- Added CovenTownTraitor.png
- Added ApocTownTraitor.png
- Added CursedSoul_Vanilla.png
- Replaced DefenseEthereal and DefenseInvincible
- Includes all changes from #43

### CODE REVIEW

**Comment by ItzLoonie** [comment]
got fking rate limited bruh

**Comment by ItzLoonie** [comment]
Needs to be looked at for any errors.

**Comment by Nidoskull** [comment]
Gave feedback on Discord, but for clarity's sake:
- Egotist Cleric, Lookout, Prosecutor, Psychic, Spy and Tracker I'm not 100% on
- Doublecheck whether or not you have all the Egotist easter eggs
- Pandora Death's ability icon shouldn't be replaced
- Unsure whether that's the correct Bugged icon in RegularBase
- Egotist modifier icon shouldn't be replaced, your replacement is less bright
- Revealed Mayor icon shouldn't be replaced, your replacement is desaturated

**Comment by ItzLoonie** [comment]
> Gave feedback on Discord, but for clarity's sake:
> 
> * Egotist Cleric, Lookout, Prosecutor, Psychic, Spy and Tracker I'm not 100% on
> * Doublecheck whether or not you have all the Egotist easter eggs
> * Pandora Death's ability icon shouldn't be replaced
> * Unsure whether that's the correct Bugged icon in RegularBase
> * Egotist modifier icon shouldn't be replaced, your replacement is less bright
> * Revealed Mayor icon shouldn't be replaced, your replacement is desaturated

- Will check those
- Checked, I do have all the Egotist easter eggs
- GitHub did a thing as I didn't change it
- Vanilla just uses Spy_Ability for the Bugged icon, and we do not have a unique asset for it yet
- Will revert
- I did not change RevealedMayor.png

**Comment by ItzLoonie** [comment]
Alright made some changes (mainly reverts).

**Pull request merged**
